### ISSUE TITLE
Esto es pecado mortal

### ISSUE THREAD

**Issue by DanBaDo** [digitolink/Curriculum#1]
https://github.com/digitolink/Curriculum/blob/ad13dac30054425833a0be96ebe08e46329940ee/src/index.html#L55-L56

Las etiquetas de los hijos se cierran antes de que se cierre el padre:
```html
<ul>
    <li><span></span></li>
</ul>
```

**Comment by digitolink** [comment]
¡Error garrafal!, sin embargo en el test no fallé esta pregunta. El problema fue cambiar cosas y probar etiquetas y al ver el resultado en el navegador correctamente se pasan errores. Como te dije en el otro issue #2  en HTML se pueden ver correctamente en el navegador códigos que no estén bien. Después de esto, estoy por ponerme el plugin para el Visual Studio Code para que se detecten los errores sintácticos. Queda:

https://github.com/digitolink/Curriculum/blob/cf2bac1feb518124768088a47268615ea9cfe223/src/index.html#L54-L56

**Comment by DanBaDo** [comment]
:+1: Recuerda cerrar los issues una vez solucionados
