### ISSUE TITLE
section

### ISSUE THREAD

**Issue by DanBaDo** [digitolink/Curriculum#2]
https://github.com/digitolink/Curriculum/blob/ad13dac30054425833a0be96ebe08e46329940ee/src/blog.html#L32-L54

Los artículos pertenecen a la sección noticias. Deberíamos de tener una única etiqueta `section` que englobe el título (`h2`) y todos los artículos de la sección.

Si no lo ves claro, avísame para comentarlo juntos. Es importante.

**Comment by digitolink** [comment]
Solucionado. Una sección para los tres artículos y no una sección para cada uno de los artículos. La página se ve exactamente igual en el navegador pero a cambio el código se ve más estructurado. En HTML a veces puedes escribir algo incorrecto y verse igual en el navegador.

https://github.com/digitolink/Curriculum/blob/cf2bac1feb518124768088a47268615ea9cfe223/src/blog.html#L30-L55

**Comment by DanBaDo** [comment]
:+1: Close the issue!
